- name: configure prod server
  hosts: prod-server
  become: true

  tasks:
  - name: update repository
    command: apt update

  - name: install docker
    command: apt install -y docker.io

  - name: start docker
    command: sudo systemctl start docker

  - name: deploy app
    command: docker run -itd -p 8084:8081 srikeshkotha/insure-me-app:1.0
